matrix:
  include:
    - os: linux
      language: c
      compiler: gcc
      env:
        BATS_PATH=submodules/bats-core/bin/bats
      script:
        - make
        - make test
    - os: linux
      language: c
      compiler: clang
      env:
        BATS_PATH=submodules/bats-core/bin/bats
      script:
        - make
        - make test
    - os: windows
      language: c
      env:
        BATS_PATH=../bin/bats
        TEXT_PREPROCESSOR=unix2dos
      install:
        - choco install --limit-output --no-progress --yes make
      script:
        - git config core.autocrlf
        - make
        - make test
    - os: osx
      language: c
      env:
        BATS_PATH=submodules/bats-core/bin/bats
      script:
        - make
        - make test
