matrix:
  include:
    - os: linux
      language: c
      compiler: gcc
      env:
        - BATS_PATH=submodules/bats-core/bin/bats
        - LINE_BREAK=
      script:
        - make
        - make test
    - os: linux
      language: c
      compiler: clang
      env:
        - BATS_PATH=submodules/bats-core/bin/bats
        - LINE_BREAK=
      script:
        - make
        - make test
    - os: windows
      language: c
      env:
        - BATS_PATH=../bin/bats
        - LINE_BREAK=\r
      install:
        - choco install --limit-output --no-progress --yes make
      script:
        - make
        - make test
    - os: osx
      language: c
      env:
        - BATS_PATH=submodules/bats-core/bin/bats
        - LINE_BREAK=
      script:
        - make
        - make test
