matrix:
  include:
    - os: linux
      language: c
      compiler: gcc
      script:
        - make
        - bash setup.bash make test
    - os: linux
      language: c
      compiler: clang
      script:
        - make
        - bash setup.bash make test
    - os: windows
      language: c
      install:
        - choco install --limit-output --no-progress --yes make
        - submodules/bats-core/install.sh ..
      script:
        - make
        - bash setup.bash make test
    - os: osx
      osx_image: xcode9.2
      language: c
      script:
        - make
        - bash setup.bash make test
