matrix:
  include:
    - os: linux
      language: c
      compiler: gcc
      script:
        - bash setup.bash 'bin/sdf_' make
    - os: linux
      language: c
      compiler: clang
      script:
        - bash setup.bash 'bin/sdf_' make
    - os: windows
      language: c
      script:
        - bash setup.bash 'bin/sdf_' mingw32-make
    - os: osx
      language: c
      script:
        - bash setup.bash 'bin/sdf_' make
