matrix:
  include:
    - os: linux
      language: c
      compiler: gcc
      install:
        - ./submodules/bats-core/install.sh bats
      script:
        - make
        - make test
    - os: linux
      language: c
      compiler: clang
      install:
        - ./submodules/bats-core/install.sh bats
      script:
        - make
        - make test
    - os: windows
      language: c
      install:
        - choco install --limit-output --no-progress --yes make
        - ./submodules/bats-core/install.sh bats
      script:
        - make
        - make test
    - os: osx
      language: c
      install:
        - ./submodules/bats-core/install.sh bats
      script:
        - make
        - make test
