matrix:
  include:
    - os: linux
      language: c
      compiler: gcc
      script:
        - make
        - bash setup.bash make test
    - os: linux
      language: c
      compiler: clang
      script:
        - make
        - bash setup.bash make test
    - os: windows
      language: c
      script:
        - mingw32-make
        - bash setup.bash mingw32-make test
    - os: osx
      language: c
      script:
        - make
        - bash setup.bash make test
