matrix:
  include:
    - os: linux
      language: c
      compiler: gcc
      install:
        - cd submodules
        - cd bats-core
        - sh install.sh ../../bats
        - cd ..
        - cd ..
      script:
        - make
        - make test
    - os: linux
      language: c
      compiler: clang
      install:
        - cd submodules
        - cd bats-core
        - sh install.sh ../../bats
        - cd ..
        - cd ..
      script:
        - make
        - make test
    - os: windows
      language: c
      install:
        - choco install --limit-output --no-progress --yes make
        - cd submodules
        - cd bats-core
        - sh install.sh ../../bats
        - cd ..
        - cd ..
      script:
        - make
        - make test
    - os: osx
      language: c
      install:
        - cd submodules
        - cd bats-core
        - sh install.sh ../../bats
        - cd ..
        - cd ..
      script:
        - make
        - make test
