matrix:
  include:
    - os: linux
      language: c
      compiler: gcc
      env:
        BATS_PATH=submodules/bats-core/bin/bats
      script:
        - make
        - make test
    - os: linux
      language: c
      compiler: clang
      env:
        BATS_PATH=submodules/bats-core/bin/bats
      script:
        - make
        - make test
    - os: windows
      language: c
      env:
        BATS_PATH=../bin/bats
      before_install:
        - git config core.autocrlf false
        - git add --renormalize .
        - git reset --hard
      install:
        - choco install --limit-output --no-progress --yes make
        - ./submodules/bats-core/install.sh ..
      script:
        - make
        - make test
    - os: osx
      language: c
      env:
        BATS_PATH=submodules/bats-core/bin/bats
      script:
        - make
        - make test
