#ifndef SDF_OPCODE_H
#define SDF_OPCODE_H

#include <stdio.h>
#include "types.h"
#include "primitive.h"

typedef sdf_u16_t sdf_opcode_t;

typedef sdf_u8_t sdf_opcode_id_t;
#define SDF_OPCODE_ID_MAX SDF_U8_MAX
#define SDF_OPCODE_ID_RANGE SDF_U8_RANGE

typedef sdf_u8_t sdf_opcode_arity_t;
#define SDF_OPCODE_ARITY_MAX 3

#define SDF_OPCODE_ID_NOT 0x00
#define SDF_OPCODE_ID_AND 0x00
#define SDF_OPCODE_ID_OR 0x01
#define SDF_OPCODE_ID_EQUAL 0x02
#define SDF_OPCODE_ID_NOT_EQUAL 0x03
#define SDF_OPCODE_ID_CONDITIONAL_BOOLEAN 0x00
#define SDF_OPCODE_ID_GREATER_THAN 0x00
#define SDF_OPCODE_ID_PARAMETER(id) (0x00 + id)
#define SDF_OPCODE_ID_PARAMETER_MIN SDF_OPCODE_PARAMETER(0)
#define SDF_OPCODE_ID_PARAMETER_MAX SDF_OPCODE_PARAMETER(SDF_U8_MAX)
#define SDF_OPCODE_ID_CONDITIONAL_NUMBER 0x00
#define SDF_OPCODE_ID_NEGATE 0x00
#define SDF_OPCODE_ID_SINE 0x01
#define SDF_OPCODE_ID_COSINE 0x02
#define SDF_OPCODE_ID_TANGENT 0x03
#define SDF_OPCODE_ID_ARC_SINE 0x04
#define SDF_OPCODE_ID_ARC_COSINE 0x05
#define SDF_OPCODE_ID_ARC_TANGENT 0x06
#define SDF_OPCODE_ID_HYPERBOLIC_SINE 0x07
#define SDF_OPCODE_ID_HYPERBOLIC_COSINE 0x08
#define SDF_OPCODE_ID_HYPERBOLIC_TANGENT 0x09
#define SDF_OPCODE_ID_HYPERBOLIC_ARC_SINE 0x0A
#define SDF_OPCODE_ID_HYPERBOLIC_ARC_COSINE 0x0B
#define SDF_OPCODE_ID_HYPERBOLIC_ARC_TANGENT 0x0C
#define SDF_OPCODE_ID_ABSOLUTE 0x0D
#define SDF_OPCODE_ID_SQUARE_ROOT 0x0E
#define SDF_OPCODE_ID_FLOOR 0x0F
#define SDF_OPCODE_ID_CEILING 0x10
#define SDF_OPCODE_ID_NATURAL_LOGARITHM 0x11
#define SDF_OPCODE_ID_LOGARITHM_10 0x12
#define SDF_OPCODE_ID_NATURAL_POWER 0x13
#define SDF_OPCODE_ID_ADD 0x00
#define SDF_OPCODE_ID_SUBTRACT 0x01
#define SDF_OPCODE_ID_MULTIPLY 0x02
#define SDF_OPCODE_ID_DIVIDE 0x03
#define SDF_OPCODE_ID_POW 0x04
#define SDF_OPCODE_ID_MODULO 0x05
#define SDF_OPCODE_ID_ARC_TANGENT_2 0x06
#define SDF_OPCODE_ID_MINIMUM 0x07
#define SDF_OPCODE_ID_MAXIMUM 0x08

#define SDF_OPCODE(result, argument_a, argument_b, argument_c, id) ((result * SDF_PRIMITIVE_RANGE * SDF_PRIMITIVE_RANGE * SDF_PRIMITIVE_RANGE * SDF_OPCODE_ID_RANGE) + (argument_a * SDF_PRIMITIVE_RANGE * SDF_PRIMITIVE_RANGE * SDF_OPCODE_ID_RANGE) + (argument_b * SDF_PRIMITIVE_RANGE * SDF_OPCODE_ID_RANGE) + (argument_c * SDF_OPCODE_ID_RANGE) + (id))

#define SDF_OPCODE_NOT SDF_OPCODE(SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_NOT)
#define SDF_OPCODE_AND SDF_OPCODE(SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_AND)
#define SDF_OPCODE_OR SDF_OPCODE(SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_OR)
#define SDF_OPCODE_EQUAL SDF_OPCODE(SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_EQUAL)
#define SDF_OPCODE_NOT_EQUAL SDF_OPCODE(SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_NOT_EQUAL)
#define SDF_OPCODE_CONDITIONAL_BOOLEAN SDF_OPCODE(SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_BOOLEAN, SDF_OPCODE_ID_CONDITIONAL_BOOLEAN)
#define SDF_OPCODE_GREATER_THAN SDF_OPCODE(SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_GREATER_THAN)
#define SDF_OPCODE_PARAMETER(id) SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, id)
#define SDF_OPCODE_PARAMETER_MIN SDF_OPCODE_PARAMETER(0)
#define SDF_OPCODE_PARAMETER_MAX SDF_OPCODE_PARAMETER(SDF_U8_MAX)
#define SDF_OPCODE_CONDITIONAL_NUMBER SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_BOOLEAN, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_OPCODE_ID_CONDITIONAL_NUMBER)
#define SDF_OPCODE_NEGATE SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_NEGATE)
#define SDF_OPCODE_SINE SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_SINE)
#define SDF_OPCODE_COSINE SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_COSINE)
#define SDF_OPCODE_TANGENT SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_TANGENT)
#define SDF_OPCODE_ARC_SINE SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_ARC_SINE)
#define SDF_OPCODE_ARC_COSINE SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_ARC_COSINE)
#define SDF_OPCODE_ARC_TANGENT SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_ARC_TANGENT)
#define SDF_OPCODE_HYPERBOLIC_SINE SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_HYPERBOLIC_SINE)
#define SDF_OPCODE_HYPERBOLIC_COSINE SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_HYPERBOLIC_COSINE)
#define SDF_OPCODE_HYPERBOLIC_TANGENT SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_HYPERBOLIC_TANGENT)
#define SDF_OPCODE_HYPERBOLIC_ARC_SINE SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_HYPERBOLIC_ARC_SINE)
#define SDF_OPCODE_HYPERBOLIC_ARC_COSINE SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_HYPERBOLIC_ARC_COSINE)
#define SDF_OPCODE_HYPERBOLIC_ARC_TANGENT SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_HYPERBOLIC_ARC_TANGENT)
#define SDF_OPCODE_ABSOLUTE SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_ABSOLUTE)
#define SDF_OPCODE_SQUARE_ROOT SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_SQUARE_ROOT)
#define SDF_OPCODE_FLOOR SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_FLOOR)
#define SDF_OPCODE_CEILING SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_CEILING)
#define SDF_OPCODE_NATURAL_LOGARITHM SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_NATURAL_LOGARITHM)
#define SDF_OPCODE_LOGARITHM_10 SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_LOGARITHM_10)
#define SDF_OPCODE_NATURAL_POWER SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_NATURAL_POWER)
#define SDF_OPCODE_ADD SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_ADD)
#define SDF_OPCODE_SUBTRACT SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_SUBTRACT)
#define SDF_OPCODE_MULTIPLY SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_MULTIPLY)
#define SDF_OPCODE_DIVIDE SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_DIVIDE)
#define SDF_OPCODE_POW SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_POW)
#define SDF_OPCODE_MODULO SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_MODULO)
#define SDF_OPCODE_ARC_TANGENT_2 SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_ARC_TANGENT_2)
#define SDF_OPCODE_MINIMUM SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_MINIMUM)
#define SDF_OPCODE_MAXIMUM SDF_OPCODE(SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NUMBER, SDF_PRIMITIVE_NONE, SDF_OPCODE_ID_MAXIMUM)

sdf_primitive_t sdf_opcode_result(
  sdf_opcode_t opcode
);

sdf_primitive_t sdf_opcode_parameter_a(
  sdf_opcode_t opcode
);

sdf_primitive_t sdf_opcode_parameter_b(
  sdf_opcode_t opcode
);

sdf_primitive_t sdf_opcode_parameter_c(
  sdf_opcode_t opcode
);

sdf_opcode_arity_t sdf_opcode_arity(
  sdf_opcode_t opcode
);

sdf_opcode_id_t sdf_opcode_id(
  sdf_opcode_t opcode
);

void sdf_opcode_print(
  FILE * file,
  sdf_opcode_t opcode
);

#endif
